      source 'http://rubygems.org'

      # Bundle edge Rails & Rack:
      gem 'rails', '3.0.0.beta3', :git => 'git://github.com/rails/rails.git'
      gem 'rack', '1.1.0', :git => 'git://github.com/rails/rack.git'

      gem 'rack-mount'
      gem 'rack-test'
      gem 'sqlite3-ruby', :require => 'sqlite3'

      # Bundle the extra gems:
 gem 'devise', '1.1.rc1' 



